//! Generates the VS Code adapter `dist/extension.js` — a Node.js module that
//! loads the WASM binary and bridges WIT imports to the VS Code API.

use crate::manifest::CoreCodeManifest;

pub fn generate(manifest: &CoreCodeManifest) -> String {
    let lang_registrations = if !manifest.languages.is_empty() {
        generate_language_registrations(&manifest.languages)
    } else {
        String::new()
    };

    let webview_code = if manifest.capabilities.webview_panels {
        generate_webview_code()
    } else {
        String::new()
    };

    format!(
        r#"// GENERATED by cargo-corecode — do not edit
const vscode = require('vscode');
const fs = require('node:fs');
const path = require('node:path');

let ext;
const channels = {{}};
const statusItems = {{}};
const panels = {{}};

{INJECT_BRIDGE}

async function activate(context) {{
  const wasmBytes = fs.readFileSync(path.join(context.extensionPath, 'dist', 'extension.wasm'));

  // Instantiate the WASM component with host imports
  const {{ instance }} = await WebAssembly.instantiate(wasmBytes, {{
    'corecode:extension/ui': {{
      log(channel, message) {{
        channels[channel] = channels[channel] ?? vscode.window.createOutputChannel(channel);
        channels[channel].appendLine(message);
      }},
      'show-message'(level, message) {{
        const fns = {{ info: 'showInformationMessage', warning: 'showWarningMessage', error: 'showErrorMessage' }};
        vscode.window[fns[level] ?? 'showInformationMessage']?.(message);
      }},
      'set-status'(id, text, tooltip) {{
        if (!text) {{ statusItems[id]?.dispose(); delete statusItems[id]; return; }}
        statusItems[id] = statusItems[id] ?? vscode.window.createStatusBarItem();
        statusItems[id].text = text;
        statusItems[id].tooltip = tooltip ?? '';
        statusItems[id].show();
      }},
    }},
    'corecode:extension/workspace': {{
      async 'read-file'(p) {{
        if (!vscode.workspace.workspaceFolders?.length) {{
          throw new Error('No workspace folder open');
        }}
        const uri = vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, p);
        const bytes = await vscode.workspace.fs.readFile(uri);
        return new TextDecoder().decode(bytes);
      }},
      async 'find-files'(glob) {{
        const uris = await vscode.workspace.findFiles(glob);
        return uris.map(u => u.toString());
      }},
      'root-uri'() {{ return vscode.workspace.workspaceFolders?.[0]?.uri.toString() ?? ''; }},
      'get-config'(key) {{
        const parts = key.split('.');
        const section = parts.slice(0, -1).join('.');
        const item = parts[parts.length - 1];
        const val = vscode.workspace.getConfiguration(section).get(item);
        return val !== undefined ? String(val) : undefined;
      }},
    }},
    {webview_code}
  }});

  ext = instance.exports;
  const result = ext['corecode:extension/lifecycle'].activate();
  if (result.tag === 'err') throw new Error(result.val);

  {lang_registrations}
  context.subscriptions.push({{ dispose: () => ext['corecode:extension/lifecycle'].deactivate() }});
}}

function deactivate() {{}}

module.exports = {{ activate, deactivate }};
"#,
        INJECT_BRIDGE = inject_vscode_bridge_fn(),
        webview_code = webview_code,
        lang_registrations = lang_registrations,
    )
}

fn inject_vscode_bridge_fn() -> &'static str {
    r#"function injectVsCodeBridge(html, webview, context) {
  const bridgeUri = webview.asWebviewUri(
    vscode.Uri.joinPath(context.extensionUri, 'webview', 'corecode-bridge.js')
  );
  const scriptTag = `<script src="${bridgeUri}"></script>`;
  const headClose = html.indexOf('</head>');
  if (headClose !== -1) {
    return html.slice(0, headClose) + scriptTag + html.slice(headClose);
  }
  const bodyClose = html.indexOf('</body>');
  if (bodyClose !== -1) {
    return html.slice(0, bodyClose) + scriptTag + html.slice(bodyClose);
  }
  return html + scriptTag;
}"#
}

fn generate_language_registrations(langs: &std::collections::HashMap<String, bool>) -> String {
    let lang_ids: Vec<&str> = langs
        .iter()
        .filter(|(_, &v)| v)
        .map(|(k, _)| k.as_str())
        .collect();

    if lang_ids.is_empty() {
        return String::new();
    }

    format!(
        r#"const langFilter = [{lang_list}];
  const lp = ext['corecode:extension/language-provider'];
  if (lp) {{
    context.subscriptions.push(
      vscode.languages.registerCompletionItemProvider(langFilter, {{
        provideCompletionItems(doc, pos, _tok, ctx) {{
          const r = lp.completions(doc.uri.toString(),
            {{ line: pos.line, character: pos.character }},
            ctx.triggerCharacter ?? null);
          if (r.tag === 'err') return [];
          return r.val.map(item => {{
            const ci = new vscode.CompletionItem(item.label);
            ci.insertText = item['insert-text'];
            ci.detail = item.detail ?? undefined;
            ci.documentation = item.documentation ?? undefined;
            return ci;
          }});
        }}
      }}),
      vscode.languages.registerHoverProvider(langFilter, {{
        provideHover(doc, pos) {{
          const r = lp.hover(doc.uri.toString(),
            {{ line: pos.line, character: pos.character }});
          if (r.tag === 'err' || !r.val) return null;
          return new vscode.Hover(r.val.contents);
        }}
      }}),
      vscode.languages.registerDocumentFormattingEditProvider(langFilter[0], {{
        provideDocumentFormattingEdits(doc) {{
          const r = lp['format-document'](doc.uri.toString(), null);
          if (r.tag === 'err') return [];
          return r.val.map(edit => vscode.TextEdit.replace(
            new vscode.Range(
              edit.range.start.line, edit.range.start.character,
              edit.range.end.line, edit.range.end.character),
            edit['new-text']
          ));
        }}
      }}),
      vscode.languages.registerDefinitionProvider(langFilter, {{
        provideDefinition(doc, pos) {{
          const r = lp.definition(doc.uri.toString(),
            {{ line: pos.line, character: pos.character }});
          if (r.tag === 'err' || !r.val) return null;
          return new vscode.Location(
            vscode.Uri.parse(r.val.uri),
            new vscode.Range(
              r.val.range.start.line, r.val.range.start.character,
              r.val.range.end.line, r.val.range.end.character));
        }}
      }}),
    );
  }}"#,
        lang_list = lang_ids
            .iter()
            .map(|l| format!("{l:?}"))
            .collect::<Vec<_>>()
            .join(", "),
    )
}

fn generate_webview_code() -> String {
    r#"'corecode:extension/webview-host': {
      'open-panel'(panelId, title, column) {
        const wp = ext['corecode:extension/webview-provider'];
        if (!wp) return { tag: 'err', val: 'no webview-provider export' };
        const html = wp['get-html'](panelId, null);
        const panel = vscode.window.createWebviewPanel(
          panelId, title, vscode.ViewColumn[column] ?? vscode.ViewColumn.One,
          { enableScripts: true, retainContextWhenHidden: true }
        );
        panel.webview.html = injectVsCodeBridge(html, panel.webview, context);
        panel.webview.onDidReceiveMessage(msg => {
          const response = wp['on-message'](panelId, JSON.stringify(msg));
          if (response) panel.webview.postMessage(JSON.parse(response));
        });
        panel.onDidDispose(() => {
          wp['on-close'](panelId);
          delete panels[panelId];
        });
        panels[panelId] = panel;
        return { tag: 'ok', val: undefined };
      },
      'post-to-webview'(panelId, json) {
        panels[panelId]?.webview.postMessage(JSON.parse(json));
        return { tag: 'ok', val: undefined };
      },
      'close-panel'(panelId) {
        panels[panelId]?.dispose();
        delete panels[panelId];
      },
    },"#
        .to_string()
}
